/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOBUF_PROTOCOL_PB_H_INCLUDED
#define PB_PROTOBUF_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _protobuf_device_type_t {
    protobuf_device_type_t_DEVICE_TYPE_UNSPECIFIED = 0,
    protobuf_device_type_t_DEVICE_TYPE_APP = 1,
    protobuf_device_type_t_DEVICE_TYPE_TX2 = 2,
    protobuf_device_type_t_DEVICE_TYPE_CONTROLLER = 3
} protobuf_device_type_t;

typedef enum _protobuf_device_addr_t {
    protobuf_device_addr_t_DEVICE_ADDR_UNSPECIFIED = 0,
    protobuf_device_addr_t_DEVICE_ADDR_APP = 1,
    protobuf_device_addr_t_DEVICE_ADDR_TX2 = 2,
    protobuf_device_addr_t_DEVICE_ADDR_CONTROLLER = 3,
    protobuf_device_addr_t_DEVICE_ADDR_DEBUG = 4,
    protobuf_device_addr_t_DEVICE_ADDR_BCAST = 5
} protobuf_device_addr_t;

typedef enum _protobuf_robot_process_state_t {
    protobuf_robot_process_state_t_ROBOT_STATE_IDLE = 0,
    protobuf_robot_process_state_t_ROBOT_STATE_RUNNING = 1
} protobuf_robot_process_state_t;

typedef enum _protobuf_robot_direct_state_t {
    protobuf_robot_direct_state_t_ROBOT_STATE_STOP = 0,
    protobuf_robot_direct_state_t_ROBOT_STATE_MOVE_FORWARD = 1,
    protobuf_robot_direct_state_t_ROBOT_STATE_TURN_RIGHT = 2,
    protobuf_robot_direct_state_t_ROBOT_STATE_TURN_LEFT = 3,
    protobuf_robot_direct_state_t_ROBOT_STATE_MOVE_BACKWARD = 4,
    protobuf_robot_direct_state_t_ROBOT_STATE_FOLLOW_LANE = 5,
    protobuf_robot_direct_state_t_ROBOT_STATE_STOP_TEMP = 6
} protobuf_robot_direct_state_t;

typedef enum _protobuf_robot_camera_state_t {
    protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_0 = 0,
    protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_P_30 = 1,
    protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_P_45 = 2,
    protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_N_30 = 3,
    protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_N_45 = 4,
    protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_MAX = 5
} protobuf_robot_camera_state_t;

typedef enum _protobuf_traffic_t {
    protobuf_traffic_t_TRAFFIC_SIGN_BUS_STOP = 0,
    protobuf_traffic_t_TRAFFIC_SIGN_CHILDREN_CROSSING = 1,
    protobuf_traffic_t_TRAFFIC_SIGN_GREEN_LIGHT = 2,
    protobuf_traffic_t_TRAFFIC_SIGN_LEFT_ONLY = 3,
    protobuf_traffic_t_TRAFFIC_SIGN_NO_STOPPING = 4,
    protobuf_traffic_t_TRAFFIC_SIGN_RED_LIGHT = 5,
    protobuf_traffic_t_TRAFFIC_SIGN_SPEED_LIMIT_40 = 6,
    protobuf_traffic_t_TRAFFIC_SIGN_STOP = 7
} protobuf_traffic_t;

typedef enum _protobuf_direction_cmd_t {
    protobuf_direction_cmd_t_DIRECTION_CMD_MOVE_FORWARD = 0,
    protobuf_direction_cmd_t_DIRECTION_CMD_MOVE_TURN_LEFT = 1,
    protobuf_direction_cmd_t_DIRECTION_CMD_MOVE_TURN_RIGHT = 2,
    protobuf_direction_cmd_t_DIRECTION_CMD_MOVE_FOLLOW_LANE = 3,
    protobuf_direction_cmd_t_DIRECTION_CMD_NONE = 4
} protobuf_direction_cmd_t;

typedef enum _protobuf_message_type_t {
    protobuf_message_type_t_MESSAGE_INFO = 0,
    protobuf_message_type_t_MESSAGE_WARN = 1,
    protobuf_message_type_t_MESSAGE_ERR = 2,
    protobuf_message_type_t_MESSAGE_NOR = 3
} protobuf_message_type_t;

typedef enum _protobuf_message_interface_dst_t {
    protobuf_message_interface_dst_t_MESSAGE_USER = 0,
    protobuf_message_interface_dst_t_MESSAGE_USER_NOTIF = 1,
    protobuf_message_interface_dst_t_MESSAGE_PROGRAMMER = 2
} protobuf_message_interface_dst_t;

/* Struct definitions */
typedef struct _protobuf_addr_t {
    protobuf_device_addr_t src;
    protobuf_device_addr_t dst;
} protobuf_addr_t;

typedef struct _protobuf_network_status_get_t {
    uint32_t dummy;
} protobuf_network_status_get_t;

typedef struct _protobuf_network_status_rsp_t {
    uint32_t dummy;
} protobuf_network_status_rsp_t;

typedef struct _protobuf_network_none_t {
    uint32_t dummy;
} protobuf_network_none_t;

typedef struct _protobuf_network_ack_t {
    uint32_t dummy;
} protobuf_network_ack_t;

typedef struct _protobuf_robot_cmd_start_t {
    uint32_t dummy;
} protobuf_robot_cmd_start_t;

typedef struct _protobuf_robot_cmd_stop_t {
    uint32_t dummy;
} protobuf_robot_cmd_stop_t;

/* *
 12 bytes */
typedef struct _protobuf_fuzzy_3_positive_rule_t {
    float PS;
    float PM;
    float PB;
} protobuf_fuzzy_3_positive_rule_t;

/* *
 20 bytes */
typedef struct _protobuf_fuzzy_5_rule_t {
    float NB;
    float NS;
    float ZE;
    float PS;
    float PB;
} protobuf_fuzzy_5_rule_t;

/* *
 28 bytes */
typedef struct _protobuf_fuzzy_7_rule_t {
    float NB;
    float NM;
    float NS;
    float ZE;
    float PS;
    float PM;
    float PB;
} protobuf_fuzzy_7_rule_t;

typedef struct _protobuf_fuzzy_9_rule_t {
    float NB;
    float NM;
    float NS;
    float NVS;
    float ZE;
    float PVS;
    float PS;
    float PM;
    float PB;
} protobuf_fuzzy_9_rule_t;

typedef struct _protobuf_fuzzy_11_rule_t {
    float NVB;
    float NB;
    float NM;
    float NS;
    float NVS;
    float ZE;
    float PVS;
    float PS;
    float PM;
    float PB;
    float PVB;
} protobuf_fuzzy_11_rule_t;

/* *
 16 bytes */
typedef struct _protobuf_fuzzy_coef_rule_t {
    float left;
    float center_left;
    float center_right;
    float right;
} protobuf_fuzzy_coef_rule_t;

/* *
 20 bytes */
typedef struct _protobuf_fuzzy_5_rule_coef_t {
    bool has_NB;
    protobuf_fuzzy_coef_rule_t NB;
    bool has_NS;
    protobuf_fuzzy_coef_rule_t NS;
    bool has_ZE;
    protobuf_fuzzy_coef_rule_t ZE;
    bool has_PS;
    protobuf_fuzzy_coef_rule_t PS;
    bool has_PB;
    protobuf_fuzzy_coef_rule_t PB;
} protobuf_fuzzy_5_rule_coef_t;

typedef struct _protobuf_fuzzy_3_rule_coef_t {
    bool has_NE;
    protobuf_fuzzy_coef_rule_t NE;
    bool has_ZE;
    protobuf_fuzzy_coef_rule_t ZE;
    bool has_PO;
    protobuf_fuzzy_coef_rule_t PO;
} protobuf_fuzzy_3_rule_coef_t;

/* *
 28 bytes */
typedef struct _protobuf_fuzzy_7_rule_coef_t {
    bool has_NB;
    protobuf_fuzzy_coef_rule_t NB;
    bool has_NM;
    protobuf_fuzzy_coef_rule_t NM;
    bool has_NS;
    protobuf_fuzzy_coef_rule_t NS;
    bool has_ZE;
    protobuf_fuzzy_coef_rule_t ZE;
    bool has_PS;
    protobuf_fuzzy_coef_rule_t PS;
    bool has_PM;
    protobuf_fuzzy_coef_rule_t PM;
    bool has_PB;
    protobuf_fuzzy_coef_rule_t PB;
} protobuf_fuzzy_7_rule_coef_t;

typedef struct _protobuf_fuzzy_11_rule_coef_t {
    bool has_NVB;
    protobuf_fuzzy_coef_rule_t NVB;
    bool has_NB;
    protobuf_fuzzy_coef_rule_t NB;
    bool has_NM;
    protobuf_fuzzy_coef_rule_t NM;
    bool has_NS;
    protobuf_fuzzy_coef_rule_t NS;
    bool has_NVS;
    protobuf_fuzzy_coef_rule_t NVS;
    bool has_ZE;
    protobuf_fuzzy_coef_rule_t ZE;
    bool has_PVS;
    protobuf_fuzzy_coef_rule_t PVS;
    bool has_PS;
    protobuf_fuzzy_coef_rule_t PS;
    bool has_PM;
    protobuf_fuzzy_coef_rule_t PM;
    bool has_PB;
    protobuf_fuzzy_coef_rule_t PB;
    bool has_PVB;
    protobuf_fuzzy_coef_rule_t PVB;
} protobuf_fuzzy_11_rule_coef_t;

/* *
 12 bytes */
typedef struct _protobuf_fuzzy_3_positive_coef_rule_t {
    bool has_PS;
    protobuf_fuzzy_coef_rule_t PS;
    bool has_PM;
    protobuf_fuzzy_coef_rule_t PM;
    bool has_PB;
    protobuf_fuzzy_coef_rule_t PB;
} protobuf_fuzzy_3_positive_coef_rule_t;

typedef struct _protobuf_fuzzy_normalization_coef_t {
    float e_nor;
    float e_dot_nor;
    float e_nor_following_state;
    float e_dot_nor_following_state;
    float e_nor_turning_state;
    float e_dot_nor_turning_state;
    float e_phi_nor;
    float theta_denor;
    float velo_nor;
    float velo_sp_denor;
} protobuf_fuzzy_normalization_coef_t;

typedef struct _protobuf_fuzzy_coef_t {
    bool has_nor_coef;
    protobuf_fuzzy_normalization_coef_t nor_coef;
    bool has_e_in_rule;
    protobuf_fuzzy_5_rule_coef_t e_in_rule;
    bool has_e_dot_in_rule;
    protobuf_fuzzy_5_rule_coef_t e_dot_in_rule;
    bool has_phi_in_rule;
    protobuf_fuzzy_3_rule_coef_t phi_in_rule;
    bool has_theta_in_rule;
    protobuf_fuzzy_5_rule_coef_t theta_in_rule;
    bool has_velo_in_rule;
    protobuf_fuzzy_3_positive_coef_rule_t velo_in_rule;
    bool has_theta_out_rule;
    protobuf_fuzzy_7_rule_t theta_out_rule;
    bool has_theta_out_3_input_rule;
    protobuf_fuzzy_9_rule_t theta_out_3_input_rule;
    bool has_velo_out_rule;
    protobuf_fuzzy_3_positive_rule_t velo_out_rule;
} protobuf_fuzzy_coef_t;

typedef struct _protobuf_fuzzy_coef_set_t {
    bool has_fuzzy_coef;
    protobuf_fuzzy_coef_t fuzzy_coef;
} protobuf_fuzzy_coef_set_t;

typedef struct _protobuf_fuzzy_coef_get_t {
    uint32_t dummy;
} protobuf_fuzzy_coef_get_t;

typedef struct _protobuf_fuzzy_coef_resp_t {
    bool has_fuzzy_coef;
    protobuf_fuzzy_coef_t fuzzy_coef;
} protobuf_fuzzy_coef_resp_t;

typedef struct _protobuf_speed_get_t {
    uint32_t dummy;
} protobuf_speed_get_t;

typedef struct _protobuf_speed_resp_t {
    float speed;
} protobuf_speed_resp_t;

typedef struct _protobuf_speed_max_set_t {
    float speed;
} protobuf_speed_max_set_t;

typedef struct _protobuf_speed_max_get_t {
    uint32_t dummy;
} protobuf_speed_max_get_t;

typedef struct _protobuf_speed_max_resp_t {
    float speed;
} protobuf_speed_max_resp_t;

typedef struct _protobuf_hdr_t {
    bool has_addr;
    protobuf_addr_t addr;
    uint64_t epoch_time;
} protobuf_hdr_t;

typedef struct _protobuf_time_get_t {
    uint32_t dummy;
} protobuf_time_get_t;

typedef struct _protobuf_time_set_t {
    uint64_t epoch_time;
} protobuf_time_set_t;

typedef struct _protobuf_time_rsp_t {
    bool time_sync;
    uint64_t epoch_time;
} protobuf_time_rsp_t;

typedef struct _protobuf_robot_process_state_get_t {
    uint32_t dummy;
} protobuf_robot_process_state_get_t;

typedef struct _protobuf_robot_process_state_set_t {
    protobuf_robot_process_state_t state;
} protobuf_robot_process_state_set_t;

typedef struct _protobuf_robot_process_state_rsp_t {
    protobuf_robot_process_state_t state;
} protobuf_robot_process_state_rsp_t;

typedef struct _protobuf_robot_direct_state_get_t {
    uint32_t dummy;
} protobuf_robot_direct_state_get_t;

typedef struct _protobuf_robot_direct_state_set_t {
    protobuf_robot_direct_state_t state;
} protobuf_robot_direct_state_set_t;

typedef struct _protobuf_robot_direct_state_rsp_t {
    protobuf_robot_direct_state_t state;
} protobuf_robot_direct_state_rsp_t;

typedef struct _protobuf_robot_state_get_t {
    uint32_t dummy;
} protobuf_robot_state_get_t;

typedef struct _protobuf_robot_state_rsp_t {
    protobuf_robot_process_state_t process_state;
    protobuf_robot_direct_state_t direct_state;
} protobuf_robot_state_rsp_t;

typedef struct _protobuf_traffic_detected_t {
    protobuf_traffic_t type;
} protobuf_traffic_detected_t;

typedef struct _protobuf_vision_coordinate_detected_t {
    float left_up_coor;
    float right_up_coor;
    float left_down_coor;
    float right_down_coor;
    float center_coor;
    float phi;
    bool is_crossing_crossroads;
    bool is_left_lane_available;
    bool is_right_lane_available;
} protobuf_vision_coordinate_detected_t;

typedef struct _protobuf_robot_control_cmd_t {
    bool has_robot_process_state_set;
    protobuf_robot_process_state_set_t robot_process_state_set;
    bool has_robot_direct_state_set;
    protobuf_robot_direct_state_set_t robot_direct_state_set;
    bool has_vision_coordinate_detected;
    protobuf_vision_coordinate_detected_t vision_coordinate_detected;
} protobuf_robot_control_cmd_t;

typedef struct _protobuf_vision_start_t {
    uint32_t dummy;
} protobuf_vision_start_t;

typedef struct _protobuf_vision_stop_t {
    uint32_t dummy;
} protobuf_vision_stop_t;

typedef struct _protobuf_robot_angle_get_t {
    uint32_t dummy;
} protobuf_robot_angle_get_t;

typedef struct _protobuf_robot_angle_rsp_t {
    float angle;
} protobuf_robot_angle_rsp_t;

typedef struct _protobuf_robot_max_angle_get_t {
    uint32_t dummy;
} protobuf_robot_max_angle_get_t;

typedef struct _protobuf_robot_max_angle_set_t {
    float angle;
} protobuf_robot_max_angle_set_t;

typedef struct _protobuf_robot_max_angle_rsp_t {
    float max_angle;
} protobuf_robot_max_angle_rsp_t;

typedef struct _protobuf_robot_info_get_t {
    uint32_t dummy;
} protobuf_robot_info_get_t;

typedef struct _protobuf_robot_state_info_t {
    protobuf_robot_process_state_t process_state;
    protobuf_robot_direct_state_t direct_state;
    protobuf_robot_direct_state_t pre_direct_state;
    protobuf_robot_camera_state_t camera_state;
} protobuf_robot_state_info_t;

typedef struct _protobuf_robot_var_info_t {
    float theta;
    float theta_nor;
    float max_theta;
    float max_setpoint_speed;
    float current_setpoint_speed;
    float current_setpoint_speed_nor;
    float current_speed;
    float current_speed_nor;
    float center;
    float left_down_coor;
    float right_down_coor;
    float left_up_coor;
    float right_up_coor;
    float e;
    float pre_e;
    float pre_e_tmp;
    float edot;
    float phi;
    float e_phi;
    float e_nor;
    float edot_nor;
    float e_phi_nor;
    uint64_t time_process;
} protobuf_robot_var_info_t;

typedef struct _protobuf_robot_info_rsp_t {
    bool has_state_info;
    protobuf_robot_state_info_t state_info;
    bool has_var_info;
    protobuf_robot_var_info_t var_info;
} protobuf_robot_info_rsp_t;

typedef PB_BYTES_ARRAY_T(200) protobuf_debug_msg_t_message_t;
typedef struct _protobuf_debug_msg_t {
    protobuf_message_type_t message_type;
    protobuf_debug_msg_t_message_t message;
    protobuf_message_interface_dst_t interface_dst;
} protobuf_debug_msg_t;

typedef struct _protobuf_robot_direction_cmd_t {
    protobuf_direction_cmd_t cmd;
} protobuf_robot_direction_cmd_t;

typedef struct _protobuf_signs_t {
    bool bus_stop;
    bool children_crossing;
    bool green_light;
    bool left_turn_only;
    bool no_stopping;
    bool red_light;
    bool speed_limit_40;
    bool stop;
} protobuf_signs_t;

typedef struct _protobuf_signs_info_t {
    bool has_signs_detected;
    protobuf_signs_t signs_detected;
    bool has_signs_obey;
    protobuf_signs_t signs_obey;
} protobuf_signs_info_t;

typedef struct _protobuf_cv_command_t {
    bool process_crossroads;
} protobuf_cv_command_t;

typedef struct _protobuf_direction_list_t {
    protobuf_direction_cmd_t first;
    protobuf_direction_cmd_t second;
    protobuf_direction_cmd_t third;
    protobuf_direction_cmd_t fourth;
    protobuf_direction_cmd_t fifth;
    protobuf_direction_cmd_t sixth;
    protobuf_direction_cmd_t seventh;
    protobuf_direction_cmd_t eighth;
    protobuf_direction_cmd_t ninth;
    protobuf_direction_cmd_t tenth;
} protobuf_direction_list_t;

typedef struct _protobuf_network_packet_t {
    bool has_hdr;
    protobuf_hdr_t hdr;
    pb_size_t which_params;
    union _protobuf_network_packet_t_params {
        protobuf_network_none_t none;
        protobuf_network_ack_t network_ack;
        protobuf_network_status_get_t network_status_get;
        protobuf_network_status_rsp_t netowrk_status_rsp;
        protobuf_robot_cmd_start_t robot_cmd_start;
        protobuf_robot_cmd_stop_t robot_cmd_stop;
        protobuf_fuzzy_coef_set_t fuzzy_coef_set;
        protobuf_fuzzy_coef_get_t fuzzy_coef_get;
        protobuf_fuzzy_coef_resp_t fuzzy_coef_resp;
        protobuf_speed_get_t speed_get;
        protobuf_speed_resp_t speed_resp;
        protobuf_speed_max_set_t speed_max_set;
        protobuf_speed_max_get_t speed_max_get;
        protobuf_speed_max_resp_t speed_max_resp;
        protobuf_time_get_t time_get;
        protobuf_time_set_t time_set;
        protobuf_time_rsp_t time_rsp;
        protobuf_robot_process_state_get_t robot_process_state_get;
        protobuf_robot_process_state_set_t robot_process_state_set;
        protobuf_robot_process_state_rsp_t robot_process_state_rsp;
        protobuf_robot_direct_state_get_t robot_direct_state_get;
        protobuf_robot_direct_state_set_t robot_direct_state_set;
        protobuf_robot_direct_state_rsp_t robot_direct_state_rsp;
        protobuf_robot_state_get_t robot_state_get;
        protobuf_robot_state_rsp_t robot_state_rsp;
        protobuf_traffic_detected_t traffic_detected;
        protobuf_vision_coordinate_detected_t vision_coordinate_detected;
        protobuf_robot_control_cmd_t robot_control_cmd;
        protobuf_vision_start_t vision_start;
        protobuf_vision_stop_t vision_stop;
        protobuf_robot_angle_get_t robot_angle_get;
        protobuf_robot_angle_rsp_t robot_angle_rsp;
        protobuf_robot_max_angle_get_t robot_max_angle_get;
        protobuf_robot_max_angle_set_t robot_max_angle_set;
        protobuf_robot_max_angle_rsp_t robot_max_angle_rsp;
        protobuf_robot_info_get_t robot_info_get;
        protobuf_robot_info_rsp_t robot_info_rsp;
        protobuf_debug_msg_t debug_msg;
        protobuf_robot_direction_cmd_t robot_direction_cmd;
        protobuf_cv_command_t cv_command;
        protobuf_signs_info_t signs_info;
        protobuf_direction_list_t direction_list;
    } params;
} protobuf_network_packet_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _protobuf_device_type_t_MIN protobuf_device_type_t_DEVICE_TYPE_UNSPECIFIED
#define _protobuf_device_type_t_MAX protobuf_device_type_t_DEVICE_TYPE_CONTROLLER
#define _protobuf_device_type_t_ARRAYSIZE ((protobuf_device_type_t)(protobuf_device_type_t_DEVICE_TYPE_CONTROLLER+1))

#define _protobuf_device_addr_t_MIN protobuf_device_addr_t_DEVICE_ADDR_UNSPECIFIED
#define _protobuf_device_addr_t_MAX protobuf_device_addr_t_DEVICE_ADDR_BCAST
#define _protobuf_device_addr_t_ARRAYSIZE ((protobuf_device_addr_t)(protobuf_device_addr_t_DEVICE_ADDR_BCAST+1))

#define _protobuf_robot_process_state_t_MIN protobuf_robot_process_state_t_ROBOT_STATE_IDLE
#define _protobuf_robot_process_state_t_MAX protobuf_robot_process_state_t_ROBOT_STATE_RUNNING
#define _protobuf_robot_process_state_t_ARRAYSIZE ((protobuf_robot_process_state_t)(protobuf_robot_process_state_t_ROBOT_STATE_RUNNING+1))

#define _protobuf_robot_direct_state_t_MIN protobuf_robot_direct_state_t_ROBOT_STATE_STOP
#define _protobuf_robot_direct_state_t_MAX protobuf_robot_direct_state_t_ROBOT_STATE_STOP_TEMP
#define _protobuf_robot_direct_state_t_ARRAYSIZE ((protobuf_robot_direct_state_t)(protobuf_robot_direct_state_t_ROBOT_STATE_STOP_TEMP+1))

#define _protobuf_robot_camera_state_t_MIN protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_0
#define _protobuf_robot_camera_state_t_MAX protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_MAX
#define _protobuf_robot_camera_state_t_ARRAYSIZE ((protobuf_robot_camera_state_t)(protobuf_robot_camera_state_t_ROBOT_CAMERA_STATE_MAX+1))

#define _protobuf_traffic_t_MIN protobuf_traffic_t_TRAFFIC_SIGN_BUS_STOP
#define _protobuf_traffic_t_MAX protobuf_traffic_t_TRAFFIC_SIGN_STOP
#define _protobuf_traffic_t_ARRAYSIZE ((protobuf_traffic_t)(protobuf_traffic_t_TRAFFIC_SIGN_STOP+1))

#define _protobuf_direction_cmd_t_MIN protobuf_direction_cmd_t_DIRECTION_CMD_MOVE_FORWARD
#define _protobuf_direction_cmd_t_MAX protobuf_direction_cmd_t_DIRECTION_CMD_NONE
#define _protobuf_direction_cmd_t_ARRAYSIZE ((protobuf_direction_cmd_t)(protobuf_direction_cmd_t_DIRECTION_CMD_NONE+1))

#define _protobuf_message_type_t_MIN protobuf_message_type_t_MESSAGE_INFO
#define _protobuf_message_type_t_MAX protobuf_message_type_t_MESSAGE_NOR
#define _protobuf_message_type_t_ARRAYSIZE ((protobuf_message_type_t)(protobuf_message_type_t_MESSAGE_NOR+1))

#define _protobuf_message_interface_dst_t_MIN protobuf_message_interface_dst_t_MESSAGE_USER
#define _protobuf_message_interface_dst_t_MAX protobuf_message_interface_dst_t_MESSAGE_PROGRAMMER
#define _protobuf_message_interface_dst_t_ARRAYSIZE ((protobuf_message_interface_dst_t)(protobuf_message_interface_dst_t_MESSAGE_PROGRAMMER+1))

#define protobuf_addr_t_src_ENUMTYPE protobuf_device_addr_t
#define protobuf_addr_t_dst_ENUMTYPE protobuf_device_addr_t

































#define protobuf_robot_process_state_set_t_state_ENUMTYPE protobuf_robot_process_state_t

#define protobuf_robot_process_state_rsp_t_state_ENUMTYPE protobuf_robot_process_state_t


#define protobuf_robot_direct_state_set_t_state_ENUMTYPE protobuf_robot_direct_state_t

#define protobuf_robot_direct_state_rsp_t_state_ENUMTYPE protobuf_robot_direct_state_t


#define protobuf_robot_state_rsp_t_process_state_ENUMTYPE protobuf_robot_process_state_t
#define protobuf_robot_state_rsp_t_direct_state_ENUMTYPE protobuf_robot_direct_state_t

#define protobuf_traffic_detected_t_type_ENUMTYPE protobuf_traffic_t











#define protobuf_robot_state_info_t_process_state_ENUMTYPE protobuf_robot_process_state_t
#define protobuf_robot_state_info_t_direct_state_ENUMTYPE protobuf_robot_direct_state_t
#define protobuf_robot_state_info_t_pre_direct_state_ENUMTYPE protobuf_robot_direct_state_t
#define protobuf_robot_state_info_t_camera_state_ENUMTYPE protobuf_robot_camera_state_t



#define protobuf_debug_msg_t_message_type_ENUMTYPE protobuf_message_type_t
#define protobuf_debug_msg_t_interface_dst_ENUMTYPE protobuf_message_interface_dst_t

#define protobuf_robot_direction_cmd_t_cmd_ENUMTYPE protobuf_direction_cmd_t




#define protobuf_direction_list_t_first_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_second_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_third_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_fourth_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_fifth_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_sixth_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_seventh_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_eighth_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_ninth_ENUMTYPE protobuf_direction_cmd_t
#define protobuf_direction_list_t_tenth_ENUMTYPE protobuf_direction_cmd_t



/* Initializer values for message structs */
#define protobuf_addr_t_init_default             {_protobuf_device_addr_t_MIN, _protobuf_device_addr_t_MIN}
#define protobuf_network_status_get_t_init_default {0}
#define protobuf_network_status_rsp_t_init_default {0}
#define protobuf_network_none_t_init_default     {0}
#define protobuf_network_ack_t_init_default      {0}
#define protobuf_robot_cmd_start_t_init_default  {0}
#define protobuf_robot_cmd_stop_t_init_default   {0}
#define protobuf_fuzzy_3_positive_rule_t_init_default {0, 0, 0}
#define protobuf_fuzzy_5_rule_t_init_default     {0, 0, 0, 0, 0}
#define protobuf_fuzzy_7_rule_t_init_default     {0, 0, 0, 0, 0, 0, 0}
#define protobuf_fuzzy_9_rule_t_init_default     {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_fuzzy_11_rule_t_init_default    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_fuzzy_coef_rule_t_init_default  {0, 0, 0, 0}
#define protobuf_fuzzy_5_rule_coef_t_init_default {false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default}
#define protobuf_fuzzy_3_rule_coef_t_init_default {false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default}
#define protobuf_fuzzy_7_rule_coef_t_init_default {false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default}
#define protobuf_fuzzy_11_rule_coef_t_init_default {false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default}
#define protobuf_fuzzy_3_positive_coef_rule_t_init_default {false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default, false, protobuf_fuzzy_coef_rule_t_init_default}
#define protobuf_fuzzy_normalization_coef_t_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_fuzzy_coef_t_init_default       {false, protobuf_fuzzy_normalization_coef_t_init_default, false, protobuf_fuzzy_5_rule_coef_t_init_default, false, protobuf_fuzzy_5_rule_coef_t_init_default, false, protobuf_fuzzy_3_rule_coef_t_init_default, false, protobuf_fuzzy_5_rule_coef_t_init_default, false, protobuf_fuzzy_3_positive_coef_rule_t_init_default, false, protobuf_fuzzy_7_rule_t_init_default, false, protobuf_fuzzy_9_rule_t_init_default, false, protobuf_fuzzy_3_positive_rule_t_init_default}
#define protobuf_fuzzy_coef_set_t_init_default   {false, protobuf_fuzzy_coef_t_init_default}
#define protobuf_fuzzy_coef_get_t_init_default   {0}
#define protobuf_fuzzy_coef_resp_t_init_default  {false, protobuf_fuzzy_coef_t_init_default}
#define protobuf_speed_get_t_init_default        {0}
#define protobuf_speed_resp_t_init_default       {0}
#define protobuf_speed_max_set_t_init_default    {0}
#define protobuf_speed_max_get_t_init_default    {0}
#define protobuf_speed_max_resp_t_init_default   {0}
#define protobuf_hdr_t_init_default              {false, protobuf_addr_t_init_default, 0}
#define protobuf_time_get_t_init_default         {0}
#define protobuf_time_set_t_init_default         {0}
#define protobuf_time_rsp_t_init_default         {0, 0}
#define protobuf_robot_process_state_get_t_init_default {0}
#define protobuf_robot_process_state_set_t_init_default {_protobuf_robot_process_state_t_MIN}
#define protobuf_robot_process_state_rsp_t_init_default {_protobuf_robot_process_state_t_MIN}
#define protobuf_robot_direct_state_get_t_init_default {0}
#define protobuf_robot_direct_state_set_t_init_default {_protobuf_robot_direct_state_t_MIN}
#define protobuf_robot_direct_state_rsp_t_init_default {_protobuf_robot_direct_state_t_MIN}
#define protobuf_robot_state_get_t_init_default  {0}
#define protobuf_robot_state_rsp_t_init_default  {_protobuf_robot_process_state_t_MIN, _protobuf_robot_direct_state_t_MIN}
#define protobuf_traffic_detected_t_init_default {_protobuf_traffic_t_MIN}
#define protobuf_vision_coordinate_detected_t_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_robot_control_cmd_t_init_default {false, protobuf_robot_process_state_set_t_init_default, false, protobuf_robot_direct_state_set_t_init_default, false, protobuf_vision_coordinate_detected_t_init_default}
#define protobuf_vision_start_t_init_default     {0}
#define protobuf_vision_stop_t_init_default      {0}
#define protobuf_robot_angle_get_t_init_default  {0}
#define protobuf_robot_angle_rsp_t_init_default  {0}
#define protobuf_robot_max_angle_get_t_init_default {0}
#define protobuf_robot_max_angle_set_t_init_default {0}
#define protobuf_robot_max_angle_rsp_t_init_default {0}
#define protobuf_robot_info_get_t_init_default   {0}
#define protobuf_robot_state_info_t_init_default {_protobuf_robot_process_state_t_MIN, _protobuf_robot_direct_state_t_MIN, _protobuf_robot_direct_state_t_MIN, _protobuf_robot_camera_state_t_MIN}
#define protobuf_robot_var_info_t_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_robot_info_rsp_t_init_default   {false, protobuf_robot_state_info_t_init_default, false, protobuf_robot_var_info_t_init_default}
#define protobuf_debug_msg_t_init_default        {_protobuf_message_type_t_MIN, {0, {0}}, _protobuf_message_interface_dst_t_MIN}
#define protobuf_robot_direction_cmd_t_init_default {_protobuf_direction_cmd_t_MIN}
#define protobuf_signs_t_init_default            {0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_signs_info_t_init_default       {false, protobuf_signs_t_init_default, false, protobuf_signs_t_init_default}
#define protobuf_cv_command_t_init_default       {0}
#define protobuf_direction_list_t_init_default   {_protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN}
#define protobuf_network_packet_t_init_default   {false, protobuf_hdr_t_init_default, 0, {protobuf_network_none_t_init_default}}
#define protobuf_addr_t_init_zero                {_protobuf_device_addr_t_MIN, _protobuf_device_addr_t_MIN}
#define protobuf_network_status_get_t_init_zero  {0}
#define protobuf_network_status_rsp_t_init_zero  {0}
#define protobuf_network_none_t_init_zero        {0}
#define protobuf_network_ack_t_init_zero         {0}
#define protobuf_robot_cmd_start_t_init_zero     {0}
#define protobuf_robot_cmd_stop_t_init_zero      {0}
#define protobuf_fuzzy_3_positive_rule_t_init_zero {0, 0, 0}
#define protobuf_fuzzy_5_rule_t_init_zero        {0, 0, 0, 0, 0}
#define protobuf_fuzzy_7_rule_t_init_zero        {0, 0, 0, 0, 0, 0, 0}
#define protobuf_fuzzy_9_rule_t_init_zero        {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_fuzzy_11_rule_t_init_zero       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_fuzzy_coef_rule_t_init_zero     {0, 0, 0, 0}
#define protobuf_fuzzy_5_rule_coef_t_init_zero   {false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero}
#define protobuf_fuzzy_3_rule_coef_t_init_zero   {false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero}
#define protobuf_fuzzy_7_rule_coef_t_init_zero   {false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero}
#define protobuf_fuzzy_11_rule_coef_t_init_zero  {false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero}
#define protobuf_fuzzy_3_positive_coef_rule_t_init_zero {false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero, false, protobuf_fuzzy_coef_rule_t_init_zero}
#define protobuf_fuzzy_normalization_coef_t_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_fuzzy_coef_t_init_zero          {false, protobuf_fuzzy_normalization_coef_t_init_zero, false, protobuf_fuzzy_5_rule_coef_t_init_zero, false, protobuf_fuzzy_5_rule_coef_t_init_zero, false, protobuf_fuzzy_3_rule_coef_t_init_zero, false, protobuf_fuzzy_5_rule_coef_t_init_zero, false, protobuf_fuzzy_3_positive_coef_rule_t_init_zero, false, protobuf_fuzzy_7_rule_t_init_zero, false, protobuf_fuzzy_9_rule_t_init_zero, false, protobuf_fuzzy_3_positive_rule_t_init_zero}
#define protobuf_fuzzy_coef_set_t_init_zero      {false, protobuf_fuzzy_coef_t_init_zero}
#define protobuf_fuzzy_coef_get_t_init_zero      {0}
#define protobuf_fuzzy_coef_resp_t_init_zero     {false, protobuf_fuzzy_coef_t_init_zero}
#define protobuf_speed_get_t_init_zero           {0}
#define protobuf_speed_resp_t_init_zero          {0}
#define protobuf_speed_max_set_t_init_zero       {0}
#define protobuf_speed_max_get_t_init_zero       {0}
#define protobuf_speed_max_resp_t_init_zero      {0}
#define protobuf_hdr_t_init_zero                 {false, protobuf_addr_t_init_zero, 0}
#define protobuf_time_get_t_init_zero            {0}
#define protobuf_time_set_t_init_zero            {0}
#define protobuf_time_rsp_t_init_zero            {0, 0}
#define protobuf_robot_process_state_get_t_init_zero {0}
#define protobuf_robot_process_state_set_t_init_zero {_protobuf_robot_process_state_t_MIN}
#define protobuf_robot_process_state_rsp_t_init_zero {_protobuf_robot_process_state_t_MIN}
#define protobuf_robot_direct_state_get_t_init_zero {0}
#define protobuf_robot_direct_state_set_t_init_zero {_protobuf_robot_direct_state_t_MIN}
#define protobuf_robot_direct_state_rsp_t_init_zero {_protobuf_robot_direct_state_t_MIN}
#define protobuf_robot_state_get_t_init_zero     {0}
#define protobuf_robot_state_rsp_t_init_zero     {_protobuf_robot_process_state_t_MIN, _protobuf_robot_direct_state_t_MIN}
#define protobuf_traffic_detected_t_init_zero    {_protobuf_traffic_t_MIN}
#define protobuf_vision_coordinate_detected_t_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_robot_control_cmd_t_init_zero   {false, protobuf_robot_process_state_set_t_init_zero, false, protobuf_robot_direct_state_set_t_init_zero, false, protobuf_vision_coordinate_detected_t_init_zero}
#define protobuf_vision_start_t_init_zero        {0}
#define protobuf_vision_stop_t_init_zero         {0}
#define protobuf_robot_angle_get_t_init_zero     {0}
#define protobuf_robot_angle_rsp_t_init_zero     {0}
#define protobuf_robot_max_angle_get_t_init_zero {0}
#define protobuf_robot_max_angle_set_t_init_zero {0}
#define protobuf_robot_max_angle_rsp_t_init_zero {0}
#define protobuf_robot_info_get_t_init_zero      {0}
#define protobuf_robot_state_info_t_init_zero    {_protobuf_robot_process_state_t_MIN, _protobuf_robot_direct_state_t_MIN, _protobuf_robot_direct_state_t_MIN, _protobuf_robot_camera_state_t_MIN}
#define protobuf_robot_var_info_t_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_robot_info_rsp_t_init_zero      {false, protobuf_robot_state_info_t_init_zero, false, protobuf_robot_var_info_t_init_zero}
#define protobuf_debug_msg_t_init_zero           {_protobuf_message_type_t_MIN, {0, {0}}, _protobuf_message_interface_dst_t_MIN}
#define protobuf_robot_direction_cmd_t_init_zero {_protobuf_direction_cmd_t_MIN}
#define protobuf_signs_t_init_zero               {0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_signs_info_t_init_zero          {false, protobuf_signs_t_init_zero, false, protobuf_signs_t_init_zero}
#define protobuf_cv_command_t_init_zero          {0}
#define protobuf_direction_list_t_init_zero      {_protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN, _protobuf_direction_cmd_t_MIN}
#define protobuf_network_packet_t_init_zero      {false, protobuf_hdr_t_init_zero, 0, {protobuf_network_none_t_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define protobuf_addr_t_src_tag                  1
#define protobuf_addr_t_dst_tag                  2
#define protobuf_network_status_get_t_dummy_tag  1
#define protobuf_network_status_rsp_t_dummy_tag  1
#define protobuf_network_none_t_dummy_tag        1
#define protobuf_network_ack_t_dummy_tag         1
#define protobuf_robot_cmd_start_t_dummy_tag     1
#define protobuf_robot_cmd_stop_t_dummy_tag      1
#define protobuf_fuzzy_3_positive_rule_t_PS_tag  1
#define protobuf_fuzzy_3_positive_rule_t_PM_tag  2
#define protobuf_fuzzy_3_positive_rule_t_PB_tag  3
#define protobuf_fuzzy_5_rule_t_NB_tag           1
#define protobuf_fuzzy_5_rule_t_NS_tag           2
#define protobuf_fuzzy_5_rule_t_ZE_tag           3
#define protobuf_fuzzy_5_rule_t_PS_tag           4
#define protobuf_fuzzy_5_rule_t_PB_tag           5
#define protobuf_fuzzy_7_rule_t_NB_tag           1
#define protobuf_fuzzy_7_rule_t_NM_tag           2
#define protobuf_fuzzy_7_rule_t_NS_tag           3
#define protobuf_fuzzy_7_rule_t_ZE_tag           4
#define protobuf_fuzzy_7_rule_t_PS_tag           5
#define protobuf_fuzzy_7_rule_t_PM_tag           6
#define protobuf_fuzzy_7_rule_t_PB_tag           7
#define protobuf_fuzzy_9_rule_t_NB_tag           1
#define protobuf_fuzzy_9_rule_t_NM_tag           2
#define protobuf_fuzzy_9_rule_t_NS_tag           3
#define protobuf_fuzzy_9_rule_t_NVS_tag          4
#define protobuf_fuzzy_9_rule_t_ZE_tag           5
#define protobuf_fuzzy_9_rule_t_PVS_tag          6
#define protobuf_fuzzy_9_rule_t_PS_tag           7
#define protobuf_fuzzy_9_rule_t_PM_tag           8
#define protobuf_fuzzy_9_rule_t_PB_tag           9
#define protobuf_fuzzy_11_rule_t_NVB_tag         1
#define protobuf_fuzzy_11_rule_t_NB_tag          2
#define protobuf_fuzzy_11_rule_t_NM_tag          3
#define protobuf_fuzzy_11_rule_t_NS_tag          4
#define protobuf_fuzzy_11_rule_t_NVS_tag         5
#define protobuf_fuzzy_11_rule_t_ZE_tag          6
#define protobuf_fuzzy_11_rule_t_PVS_tag         7
#define protobuf_fuzzy_11_rule_t_PS_tag          8
#define protobuf_fuzzy_11_rule_t_PM_tag          9
#define protobuf_fuzzy_11_rule_t_PB_tag          10
#define protobuf_fuzzy_11_rule_t_PVB_tag         11
#define protobuf_fuzzy_coef_rule_t_left_tag      1
#define protobuf_fuzzy_coef_rule_t_center_left_tag 2
#define protobuf_fuzzy_coef_rule_t_center_right_tag 3
#define protobuf_fuzzy_coef_rule_t_right_tag     4
#define protobuf_fuzzy_5_rule_coef_t_NB_tag      1
#define protobuf_fuzzy_5_rule_coef_t_NS_tag      2
#define protobuf_fuzzy_5_rule_coef_t_ZE_tag      3
#define protobuf_fuzzy_5_rule_coef_t_PS_tag      4
#define protobuf_fuzzy_5_rule_coef_t_PB_tag      5
#define protobuf_fuzzy_3_rule_coef_t_NE_tag      1
#define protobuf_fuzzy_3_rule_coef_t_ZE_tag      2
#define protobuf_fuzzy_3_rule_coef_t_PO_tag      3
#define protobuf_fuzzy_7_rule_coef_t_NB_tag      1
#define protobuf_fuzzy_7_rule_coef_t_NM_tag      2
#define protobuf_fuzzy_7_rule_coef_t_NS_tag      3
#define protobuf_fuzzy_7_rule_coef_t_ZE_tag      4
#define protobuf_fuzzy_7_rule_coef_t_PS_tag      5
#define protobuf_fuzzy_7_rule_coef_t_PM_tag      6
#define protobuf_fuzzy_7_rule_coef_t_PB_tag      7
#define protobuf_fuzzy_11_rule_coef_t_NVB_tag    1
#define protobuf_fuzzy_11_rule_coef_t_NB_tag     2
#define protobuf_fuzzy_11_rule_coef_t_NM_tag     3
#define protobuf_fuzzy_11_rule_coef_t_NS_tag     4
#define protobuf_fuzzy_11_rule_coef_t_NVS_tag    5
#define protobuf_fuzzy_11_rule_coef_t_ZE_tag     6
#define protobuf_fuzzy_11_rule_coef_t_PVS_tag    7
#define protobuf_fuzzy_11_rule_coef_t_PS_tag     8
#define protobuf_fuzzy_11_rule_coef_t_PM_tag     9
#define protobuf_fuzzy_11_rule_coef_t_PB_tag     10
#define protobuf_fuzzy_11_rule_coef_t_PVB_tag    11
#define protobuf_fuzzy_3_positive_coef_rule_t_PS_tag 1
#define protobuf_fuzzy_3_positive_coef_rule_t_PM_tag 2
#define protobuf_fuzzy_3_positive_coef_rule_t_PB_tag 3
#define protobuf_fuzzy_normalization_coef_t_e_nor_tag 1
#define protobuf_fuzzy_normalization_coef_t_e_dot_nor_tag 2
#define protobuf_fuzzy_normalization_coef_t_e_nor_following_state_tag 3
#define protobuf_fuzzy_normalization_coef_t_e_dot_nor_following_state_tag 4
#define protobuf_fuzzy_normalization_coef_t_e_nor_turning_state_tag 5
#define protobuf_fuzzy_normalization_coef_t_e_dot_nor_turning_state_tag 6
#define protobuf_fuzzy_normalization_coef_t_e_phi_nor_tag 7
#define protobuf_fuzzy_normalization_coef_t_theta_denor_tag 9
#define protobuf_fuzzy_normalization_coef_t_velo_nor_tag 10
#define protobuf_fuzzy_normalization_coef_t_velo_sp_denor_tag 11
#define protobuf_fuzzy_coef_t_nor_coef_tag       1
#define protobuf_fuzzy_coef_t_e_in_rule_tag      2
#define protobuf_fuzzy_coef_t_e_dot_in_rule_tag  3
#define protobuf_fuzzy_coef_t_phi_in_rule_tag    4
#define protobuf_fuzzy_coef_t_theta_in_rule_tag  5
#define protobuf_fuzzy_coef_t_velo_in_rule_tag   6
#define protobuf_fuzzy_coef_t_theta_out_rule_tag 7
#define protobuf_fuzzy_coef_t_theta_out_3_input_rule_tag 8
#define protobuf_fuzzy_coef_t_velo_out_rule_tag  9
#define protobuf_fuzzy_coef_set_t_fuzzy_coef_tag 1
#define protobuf_fuzzy_coef_get_t_dummy_tag      1
#define protobuf_fuzzy_coef_resp_t_fuzzy_coef_tag 1
#define protobuf_speed_get_t_dummy_tag           1
#define protobuf_speed_resp_t_speed_tag          1
#define protobuf_speed_max_set_t_speed_tag       1
#define protobuf_speed_max_get_t_dummy_tag       1
#define protobuf_speed_max_resp_t_speed_tag      1
#define protobuf_hdr_t_addr_tag                  1
#define protobuf_hdr_t_epoch_time_tag            2
#define protobuf_time_get_t_dummy_tag            1
#define protobuf_time_set_t_epoch_time_tag       1
#define protobuf_time_rsp_t_time_sync_tag        1
#define protobuf_time_rsp_t_epoch_time_tag       2
#define protobuf_robot_process_state_get_t_dummy_tag 1
#define protobuf_robot_process_state_set_t_state_tag 1
#define protobuf_robot_process_state_rsp_t_state_tag 1
#define protobuf_robot_direct_state_get_t_dummy_tag 1
#define protobuf_robot_direct_state_set_t_state_tag 1
#define protobuf_robot_direct_state_rsp_t_state_tag 1
#define protobuf_robot_state_get_t_dummy_tag     1
#define protobuf_robot_state_rsp_t_process_state_tag 1
#define protobuf_robot_state_rsp_t_direct_state_tag 2
#define protobuf_traffic_detected_t_type_tag     1
#define protobuf_vision_coordinate_detected_t_left_up_coor_tag 1
#define protobuf_vision_coordinate_detected_t_right_up_coor_tag 2
#define protobuf_vision_coordinate_detected_t_left_down_coor_tag 3
#define protobuf_vision_coordinate_detected_t_right_down_coor_tag 4
#define protobuf_vision_coordinate_detected_t_center_coor_tag 5
#define protobuf_vision_coordinate_detected_t_phi_tag 6
#define protobuf_vision_coordinate_detected_t_is_crossing_crossroads_tag 7
#define protobuf_vision_coordinate_detected_t_is_left_lane_available_tag 8
#define protobuf_vision_coordinate_detected_t_is_right_lane_available_tag 9
#define protobuf_robot_control_cmd_t_robot_process_state_set_tag 1
#define protobuf_robot_control_cmd_t_robot_direct_state_set_tag 2
#define protobuf_robot_control_cmd_t_vision_coordinate_detected_tag 3
#define protobuf_vision_start_t_dummy_tag        1
#define protobuf_vision_stop_t_dummy_tag         1
#define protobuf_robot_angle_get_t_dummy_tag     1
#define protobuf_robot_angle_rsp_t_angle_tag     1
#define protobuf_robot_max_angle_get_t_dummy_tag 1
#define protobuf_robot_max_angle_set_t_angle_tag 1
#define protobuf_robot_max_angle_rsp_t_max_angle_tag 1
#define protobuf_robot_info_get_t_dummy_tag      1
#define protobuf_robot_state_info_t_process_state_tag 1
#define protobuf_robot_state_info_t_direct_state_tag 2
#define protobuf_robot_state_info_t_pre_direct_state_tag 3
#define protobuf_robot_state_info_t_camera_state_tag 4
#define protobuf_robot_var_info_t_theta_tag      1
#define protobuf_robot_var_info_t_theta_nor_tag  2
#define protobuf_robot_var_info_t_max_theta_tag  3
#define protobuf_robot_var_info_t_max_setpoint_speed_tag 4
#define protobuf_robot_var_info_t_current_setpoint_speed_tag 5
#define protobuf_robot_var_info_t_current_setpoint_speed_nor_tag 6
#define protobuf_robot_var_info_t_current_speed_tag 7
#define protobuf_robot_var_info_t_current_speed_nor_tag 8
#define protobuf_robot_var_info_t_center_tag     9
#define protobuf_robot_var_info_t_left_down_coor_tag 10
#define protobuf_robot_var_info_t_right_down_coor_tag 11
#define protobuf_robot_var_info_t_left_up_coor_tag 12
#define protobuf_robot_var_info_t_right_up_coor_tag 13
#define protobuf_robot_var_info_t_e_tag          14
#define protobuf_robot_var_info_t_pre_e_tag      15
#define protobuf_robot_var_info_t_pre_e_tmp_tag  16
#define protobuf_robot_var_info_t_edot_tag       17
#define protobuf_robot_var_info_t_phi_tag        18
#define protobuf_robot_var_info_t_e_phi_tag      19
#define protobuf_robot_var_info_t_e_nor_tag      20
#define protobuf_robot_var_info_t_edot_nor_tag   21
#define protobuf_robot_var_info_t_e_phi_nor_tag  22
#define protobuf_robot_var_info_t_time_process_tag 23
#define protobuf_robot_info_rsp_t_state_info_tag 1
#define protobuf_robot_info_rsp_t_var_info_tag   2
#define protobuf_debug_msg_t_message_type_tag    1
#define protobuf_debug_msg_t_message_tag         2
#define protobuf_debug_msg_t_interface_dst_tag   3
#define protobuf_robot_direction_cmd_t_cmd_tag   1
#define protobuf_signs_t_bus_stop_tag            1
#define protobuf_signs_t_children_crossing_tag   2
#define protobuf_signs_t_green_light_tag         3
#define protobuf_signs_t_left_turn_only_tag      4
#define protobuf_signs_t_no_stopping_tag         5
#define protobuf_signs_t_red_light_tag           6
#define protobuf_signs_t_speed_limit_40_tag      7
#define protobuf_signs_t_stop_tag                8
#define protobuf_signs_info_t_signs_detected_tag 1
#define protobuf_signs_info_t_signs_obey_tag     2
#define protobuf_cv_command_t_process_crossroads_tag 1
#define protobuf_direction_list_t_first_tag      1
#define protobuf_direction_list_t_second_tag     2
#define protobuf_direction_list_t_third_tag      3
#define protobuf_direction_list_t_fourth_tag     4
#define protobuf_direction_list_t_fifth_tag      5
#define protobuf_direction_list_t_sixth_tag      6
#define protobuf_direction_list_t_seventh_tag    7
#define protobuf_direction_list_t_eighth_tag     8
#define protobuf_direction_list_t_ninth_tag      9
#define protobuf_direction_list_t_tenth_tag      10
#define protobuf_network_packet_t_hdr_tag        1
#define protobuf_network_packet_t_none_tag       2
#define protobuf_network_packet_t_network_ack_tag 3
#define protobuf_network_packet_t_network_status_get_tag 4
#define protobuf_network_packet_t_netowrk_status_rsp_tag 5
#define protobuf_network_packet_t_robot_cmd_start_tag 6
#define protobuf_network_packet_t_robot_cmd_stop_tag 7
#define protobuf_network_packet_t_fuzzy_coef_set_tag 8
#define protobuf_network_packet_t_fuzzy_coef_get_tag 9
#define protobuf_network_packet_t_fuzzy_coef_resp_tag 10
#define protobuf_network_packet_t_speed_get_tag  11
#define protobuf_network_packet_t_speed_resp_tag 12
#define protobuf_network_packet_t_speed_max_set_tag 13
#define protobuf_network_packet_t_speed_max_get_tag 14
#define protobuf_network_packet_t_speed_max_resp_tag 15
#define protobuf_network_packet_t_time_get_tag   16
#define protobuf_network_packet_t_time_set_tag   17
#define protobuf_network_packet_t_time_rsp_tag   18
#define protobuf_network_packet_t_robot_process_state_get_tag 19
#define protobuf_network_packet_t_robot_process_state_set_tag 20
#define protobuf_network_packet_t_robot_process_state_rsp_tag 21
#define protobuf_network_packet_t_robot_direct_state_get_tag 22
#define protobuf_network_packet_t_robot_direct_state_set_tag 23
#define protobuf_network_packet_t_robot_direct_state_rsp_tag 24
#define protobuf_network_packet_t_robot_state_get_tag 25
#define protobuf_network_packet_t_robot_state_rsp_tag 26
#define protobuf_network_packet_t_traffic_detected_tag 27
#define protobuf_network_packet_t_vision_coordinate_detected_tag 28
#define protobuf_network_packet_t_robot_control_cmd_tag 29
#define protobuf_network_packet_t_vision_start_tag 30
#define protobuf_network_packet_t_vision_stop_tag 31
#define protobuf_network_packet_t_robot_angle_get_tag 32
#define protobuf_network_packet_t_robot_angle_rsp_tag 33
#define protobuf_network_packet_t_robot_max_angle_get_tag 34
#define protobuf_network_packet_t_robot_max_angle_set_tag 35
#define protobuf_network_packet_t_robot_max_angle_rsp_tag 36
#define protobuf_network_packet_t_robot_info_get_tag 37
#define protobuf_network_packet_t_robot_info_rsp_tag 38
#define protobuf_network_packet_t_debug_msg_tag  39
#define protobuf_network_packet_t_robot_direction_cmd_tag 40
#define protobuf_network_packet_t_cv_command_tag 41
#define protobuf_network_packet_t_signs_info_tag 42
#define protobuf_network_packet_t_direction_list_tag 43

/* Struct field encoding specification for nanopb */
#define protobuf_addr_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    src,               1) \
X(a, STATIC,   SINGULAR, UENUM,    dst,               2)
#define protobuf_addr_t_CALLBACK NULL
#define protobuf_addr_t_DEFAULT NULL

#define protobuf_network_status_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_network_status_get_t_CALLBACK NULL
#define protobuf_network_status_get_t_DEFAULT NULL

#define protobuf_network_status_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_network_status_rsp_t_CALLBACK NULL
#define protobuf_network_status_rsp_t_DEFAULT NULL

#define protobuf_network_none_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_network_none_t_CALLBACK NULL
#define protobuf_network_none_t_DEFAULT NULL

#define protobuf_network_ack_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_network_ack_t_CALLBACK NULL
#define protobuf_network_ack_t_DEFAULT NULL

#define protobuf_robot_cmd_start_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_robot_cmd_start_t_CALLBACK NULL
#define protobuf_robot_cmd_start_t_DEFAULT NULL

#define protobuf_robot_cmd_stop_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_robot_cmd_stop_t_CALLBACK NULL
#define protobuf_robot_cmd_stop_t_DEFAULT NULL

#define protobuf_fuzzy_3_positive_rule_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    PS,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    PM,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    PB,                3)
#define protobuf_fuzzy_3_positive_rule_t_CALLBACK NULL
#define protobuf_fuzzy_3_positive_rule_t_DEFAULT NULL

#define protobuf_fuzzy_5_rule_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    NB,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    NS,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    ZE,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    PS,                4) \
X(a, STATIC,   SINGULAR, FLOAT,    PB,                5)
#define protobuf_fuzzy_5_rule_t_CALLBACK NULL
#define protobuf_fuzzy_5_rule_t_DEFAULT NULL

#define protobuf_fuzzy_7_rule_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    NB,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    NM,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    NS,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    ZE,                4) \
X(a, STATIC,   SINGULAR, FLOAT,    PS,                5) \
X(a, STATIC,   SINGULAR, FLOAT,    PM,                6) \
X(a, STATIC,   SINGULAR, FLOAT,    PB,                7)
#define protobuf_fuzzy_7_rule_t_CALLBACK NULL
#define protobuf_fuzzy_7_rule_t_DEFAULT NULL

#define protobuf_fuzzy_9_rule_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    NB,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    NM,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    NS,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    NVS,               4) \
X(a, STATIC,   SINGULAR, FLOAT,    ZE,                5) \
X(a, STATIC,   SINGULAR, FLOAT,    PVS,               6) \
X(a, STATIC,   SINGULAR, FLOAT,    PS,                7) \
X(a, STATIC,   SINGULAR, FLOAT,    PM,                8) \
X(a, STATIC,   SINGULAR, FLOAT,    PB,                9)
#define protobuf_fuzzy_9_rule_t_CALLBACK NULL
#define protobuf_fuzzy_9_rule_t_DEFAULT NULL

#define protobuf_fuzzy_11_rule_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    NVB,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    NB,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    NM,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    NS,                4) \
X(a, STATIC,   SINGULAR, FLOAT,    NVS,               5) \
X(a, STATIC,   SINGULAR, FLOAT,    ZE,                6) \
X(a, STATIC,   SINGULAR, FLOAT,    PVS,               7) \
X(a, STATIC,   SINGULAR, FLOAT,    PS,                8) \
X(a, STATIC,   SINGULAR, FLOAT,    PM,                9) \
X(a, STATIC,   SINGULAR, FLOAT,    PB,               10) \
X(a, STATIC,   SINGULAR, FLOAT,    PVB,              11)
#define protobuf_fuzzy_11_rule_t_CALLBACK NULL
#define protobuf_fuzzy_11_rule_t_DEFAULT NULL

#define protobuf_fuzzy_coef_rule_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    left,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    center_left,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    center_right,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    right,             4)
#define protobuf_fuzzy_coef_rule_t_CALLBACK NULL
#define protobuf_fuzzy_coef_rule_t_DEFAULT NULL

#define protobuf_fuzzy_5_rule_coef_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NB,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NS,                2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ZE,                3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PS,                4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PB,                5)
#define protobuf_fuzzy_5_rule_coef_t_CALLBACK NULL
#define protobuf_fuzzy_5_rule_coef_t_DEFAULT NULL
#define protobuf_fuzzy_5_rule_coef_t_NB_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_5_rule_coef_t_NS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_5_rule_coef_t_ZE_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_5_rule_coef_t_PS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_5_rule_coef_t_PB_MSGTYPE protobuf_fuzzy_coef_rule_t

#define protobuf_fuzzy_3_rule_coef_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NE,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ZE,                2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PO,                3)
#define protobuf_fuzzy_3_rule_coef_t_CALLBACK NULL
#define protobuf_fuzzy_3_rule_coef_t_DEFAULT NULL
#define protobuf_fuzzy_3_rule_coef_t_NE_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_3_rule_coef_t_ZE_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_3_rule_coef_t_PO_MSGTYPE protobuf_fuzzy_coef_rule_t

#define protobuf_fuzzy_7_rule_coef_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NB,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NM,                2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NS,                3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ZE,                4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PS,                5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PM,                6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PB,                7)
#define protobuf_fuzzy_7_rule_coef_t_CALLBACK NULL
#define protobuf_fuzzy_7_rule_coef_t_DEFAULT NULL
#define protobuf_fuzzy_7_rule_coef_t_NB_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_7_rule_coef_t_NM_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_7_rule_coef_t_NS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_7_rule_coef_t_ZE_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_7_rule_coef_t_PS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_7_rule_coef_t_PM_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_7_rule_coef_t_PB_MSGTYPE protobuf_fuzzy_coef_rule_t

#define protobuf_fuzzy_11_rule_coef_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NVB,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NB,                2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NM,                3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NS,                4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  NVS,               5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ZE,                6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PVS,               7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PS,                8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PM,                9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PB,               10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PVB,              11)
#define protobuf_fuzzy_11_rule_coef_t_CALLBACK NULL
#define protobuf_fuzzy_11_rule_coef_t_DEFAULT NULL
#define protobuf_fuzzy_11_rule_coef_t_NVB_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_NB_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_NM_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_NS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_NVS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_ZE_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_PVS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_PS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_PM_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_PB_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_11_rule_coef_t_PVB_MSGTYPE protobuf_fuzzy_coef_rule_t

#define protobuf_fuzzy_3_positive_coef_rule_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PS,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PM,                2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  PB,                3)
#define protobuf_fuzzy_3_positive_coef_rule_t_CALLBACK NULL
#define protobuf_fuzzy_3_positive_coef_rule_t_DEFAULT NULL
#define protobuf_fuzzy_3_positive_coef_rule_t_PS_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_3_positive_coef_rule_t_PM_MSGTYPE protobuf_fuzzy_coef_rule_t
#define protobuf_fuzzy_3_positive_coef_rule_t_PB_MSGTYPE protobuf_fuzzy_coef_rule_t

#define protobuf_fuzzy_normalization_coef_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    e_nor,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    e_dot_nor,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    e_nor_following_state,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    e_dot_nor_following_state,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    e_nor_turning_state,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    e_dot_nor_turning_state,   6) \
X(a, STATIC,   SINGULAR, FLOAT,    e_phi_nor,         7) \
X(a, STATIC,   SINGULAR, FLOAT,    theta_denor,       9) \
X(a, STATIC,   SINGULAR, FLOAT,    velo_nor,         10) \
X(a, STATIC,   SINGULAR, FLOAT,    velo_sp_denor,    11)
#define protobuf_fuzzy_normalization_coef_t_CALLBACK NULL
#define protobuf_fuzzy_normalization_coef_t_DEFAULT NULL

#define protobuf_fuzzy_coef_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  nor_coef,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  e_in_rule,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  e_dot_in_rule,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  phi_in_rule,       4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  theta_in_rule,     5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  velo_in_rule,      6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  theta_out_rule,    7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  theta_out_3_input_rule,   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  velo_out_rule,     9)
#define protobuf_fuzzy_coef_t_CALLBACK NULL
#define protobuf_fuzzy_coef_t_DEFAULT NULL
#define protobuf_fuzzy_coef_t_nor_coef_MSGTYPE protobuf_fuzzy_normalization_coef_t
#define protobuf_fuzzy_coef_t_e_in_rule_MSGTYPE protobuf_fuzzy_5_rule_coef_t
#define protobuf_fuzzy_coef_t_e_dot_in_rule_MSGTYPE protobuf_fuzzy_5_rule_coef_t
#define protobuf_fuzzy_coef_t_phi_in_rule_MSGTYPE protobuf_fuzzy_3_rule_coef_t
#define protobuf_fuzzy_coef_t_theta_in_rule_MSGTYPE protobuf_fuzzy_5_rule_coef_t
#define protobuf_fuzzy_coef_t_velo_in_rule_MSGTYPE protobuf_fuzzy_3_positive_coef_rule_t
#define protobuf_fuzzy_coef_t_theta_out_rule_MSGTYPE protobuf_fuzzy_7_rule_t
#define protobuf_fuzzy_coef_t_theta_out_3_input_rule_MSGTYPE protobuf_fuzzy_9_rule_t
#define protobuf_fuzzy_coef_t_velo_out_rule_MSGTYPE protobuf_fuzzy_3_positive_rule_t

#define protobuf_fuzzy_coef_set_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fuzzy_coef,        1)
#define protobuf_fuzzy_coef_set_t_CALLBACK NULL
#define protobuf_fuzzy_coef_set_t_DEFAULT NULL
#define protobuf_fuzzy_coef_set_t_fuzzy_coef_MSGTYPE protobuf_fuzzy_coef_t

#define protobuf_fuzzy_coef_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_fuzzy_coef_get_t_CALLBACK NULL
#define protobuf_fuzzy_coef_get_t_DEFAULT NULL

#define protobuf_fuzzy_coef_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fuzzy_coef,        1)
#define protobuf_fuzzy_coef_resp_t_CALLBACK NULL
#define protobuf_fuzzy_coef_resp_t_DEFAULT NULL
#define protobuf_fuzzy_coef_resp_t_fuzzy_coef_MSGTYPE protobuf_fuzzy_coef_t

#define protobuf_speed_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_speed_get_t_CALLBACK NULL
#define protobuf_speed_get_t_DEFAULT NULL

#define protobuf_speed_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1)
#define protobuf_speed_resp_t_CALLBACK NULL
#define protobuf_speed_resp_t_DEFAULT NULL

#define protobuf_speed_max_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1)
#define protobuf_speed_max_set_t_CALLBACK NULL
#define protobuf_speed_max_set_t_DEFAULT NULL

#define protobuf_speed_max_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_speed_max_get_t_CALLBACK NULL
#define protobuf_speed_max_get_t_DEFAULT NULL

#define protobuf_speed_max_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1)
#define protobuf_speed_max_resp_t_CALLBACK NULL
#define protobuf_speed_max_resp_t_DEFAULT NULL

#define protobuf_hdr_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  addr,              1) \
X(a, STATIC,   SINGULAR, UINT64,   epoch_time,        2)
#define protobuf_hdr_t_CALLBACK NULL
#define protobuf_hdr_t_DEFAULT NULL
#define protobuf_hdr_t_addr_MSGTYPE protobuf_addr_t

#define protobuf_time_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_time_get_t_CALLBACK NULL
#define protobuf_time_get_t_DEFAULT NULL

#define protobuf_time_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   epoch_time,        1)
#define protobuf_time_set_t_CALLBACK NULL
#define protobuf_time_set_t_DEFAULT NULL

#define protobuf_time_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     time_sync,         1) \
X(a, STATIC,   SINGULAR, UINT64,   epoch_time,        2)
#define protobuf_time_rsp_t_CALLBACK NULL
#define protobuf_time_rsp_t_DEFAULT NULL

#define protobuf_robot_process_state_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_robot_process_state_get_t_CALLBACK NULL
#define protobuf_robot_process_state_get_t_DEFAULT NULL

#define protobuf_robot_process_state_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1)
#define protobuf_robot_process_state_set_t_CALLBACK NULL
#define protobuf_robot_process_state_set_t_DEFAULT NULL

#define protobuf_robot_process_state_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1)
#define protobuf_robot_process_state_rsp_t_CALLBACK NULL
#define protobuf_robot_process_state_rsp_t_DEFAULT NULL

#define protobuf_robot_direct_state_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_robot_direct_state_get_t_CALLBACK NULL
#define protobuf_robot_direct_state_get_t_DEFAULT NULL

#define protobuf_robot_direct_state_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1)
#define protobuf_robot_direct_state_set_t_CALLBACK NULL
#define protobuf_robot_direct_state_set_t_DEFAULT NULL

#define protobuf_robot_direct_state_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1)
#define protobuf_robot_direct_state_rsp_t_CALLBACK NULL
#define protobuf_robot_direct_state_rsp_t_DEFAULT NULL

#define protobuf_robot_state_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_robot_state_get_t_CALLBACK NULL
#define protobuf_robot_state_get_t_DEFAULT NULL

#define protobuf_robot_state_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    process_state,     1) \
X(a, STATIC,   SINGULAR, UENUM,    direct_state,      2)
#define protobuf_robot_state_rsp_t_CALLBACK NULL
#define protobuf_robot_state_rsp_t_DEFAULT NULL

#define protobuf_traffic_detected_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define protobuf_traffic_detected_t_CALLBACK NULL
#define protobuf_traffic_detected_t_DEFAULT NULL

#define protobuf_vision_coordinate_detected_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    left_up_coor,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    right_up_coor,     2) \
X(a, STATIC,   SINGULAR, FLOAT,    left_down_coor,    3) \
X(a, STATIC,   SINGULAR, FLOAT,    right_down_coor,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    center_coor,       5) \
X(a, STATIC,   SINGULAR, FLOAT,    phi,               6) \
X(a, STATIC,   SINGULAR, BOOL,     is_crossing_crossroads,   7) \
X(a, STATIC,   SINGULAR, BOOL,     is_left_lane_available,   8) \
X(a, STATIC,   SINGULAR, BOOL,     is_right_lane_available,   9)
#define protobuf_vision_coordinate_detected_t_CALLBACK NULL
#define protobuf_vision_coordinate_detected_t_DEFAULT NULL

#define protobuf_robot_control_cmd_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  robot_process_state_set,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  robot_direct_state_set,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vision_coordinate_detected,   3)
#define protobuf_robot_control_cmd_t_CALLBACK NULL
#define protobuf_robot_control_cmd_t_DEFAULT NULL
#define protobuf_robot_control_cmd_t_robot_process_state_set_MSGTYPE protobuf_robot_process_state_set_t
#define protobuf_robot_control_cmd_t_robot_direct_state_set_MSGTYPE protobuf_robot_direct_state_set_t
#define protobuf_robot_control_cmd_t_vision_coordinate_detected_MSGTYPE protobuf_vision_coordinate_detected_t

#define protobuf_vision_start_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_vision_start_t_CALLBACK NULL
#define protobuf_vision_start_t_DEFAULT NULL

#define protobuf_vision_stop_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_vision_stop_t_CALLBACK NULL
#define protobuf_vision_stop_t_DEFAULT NULL

#define protobuf_robot_angle_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_robot_angle_get_t_CALLBACK NULL
#define protobuf_robot_angle_get_t_DEFAULT NULL

#define protobuf_robot_angle_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle,             1)
#define protobuf_robot_angle_rsp_t_CALLBACK NULL
#define protobuf_robot_angle_rsp_t_DEFAULT NULL

#define protobuf_robot_max_angle_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_robot_max_angle_get_t_CALLBACK NULL
#define protobuf_robot_max_angle_get_t_DEFAULT NULL

#define protobuf_robot_max_angle_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle,             1)
#define protobuf_robot_max_angle_set_t_CALLBACK NULL
#define protobuf_robot_max_angle_set_t_DEFAULT NULL

#define protobuf_robot_max_angle_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    max_angle,         1)
#define protobuf_robot_max_angle_rsp_t_CALLBACK NULL
#define protobuf_robot_max_angle_rsp_t_DEFAULT NULL

#define protobuf_robot_info_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_robot_info_get_t_CALLBACK NULL
#define protobuf_robot_info_get_t_DEFAULT NULL

#define protobuf_robot_state_info_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    process_state,     1) \
X(a, STATIC,   SINGULAR, UENUM,    direct_state,      2) \
X(a, STATIC,   SINGULAR, UENUM,    pre_direct_state,   3) \
X(a, STATIC,   SINGULAR, UENUM,    camera_state,      4)
#define protobuf_robot_state_info_t_CALLBACK NULL
#define protobuf_robot_state_info_t_DEFAULT NULL

#define protobuf_robot_var_info_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    theta,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    theta_nor,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    max_theta,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    max_setpoint_speed,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    current_setpoint_speed,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    current_setpoint_speed_nor,   6) \
X(a, STATIC,   SINGULAR, FLOAT,    current_speed,     7) \
X(a, STATIC,   SINGULAR, FLOAT,    current_speed_nor,   8) \
X(a, STATIC,   SINGULAR, FLOAT,    center,            9) \
X(a, STATIC,   SINGULAR, FLOAT,    left_down_coor,   10) \
X(a, STATIC,   SINGULAR, FLOAT,    right_down_coor,  11) \
X(a, STATIC,   SINGULAR, FLOAT,    left_up_coor,     12) \
X(a, STATIC,   SINGULAR, FLOAT,    right_up_coor,    13) \
X(a, STATIC,   SINGULAR, FLOAT,    e,                14) \
X(a, STATIC,   SINGULAR, FLOAT,    pre_e,            15) \
X(a, STATIC,   SINGULAR, FLOAT,    pre_e_tmp,        16) \
X(a, STATIC,   SINGULAR, FLOAT,    edot,             17) \
X(a, STATIC,   SINGULAR, FLOAT,    phi,              18) \
X(a, STATIC,   SINGULAR, FLOAT,    e_phi,            19) \
X(a, STATIC,   SINGULAR, FLOAT,    e_nor,            20) \
X(a, STATIC,   SINGULAR, FLOAT,    edot_nor,         21) \
X(a, STATIC,   SINGULAR, FLOAT,    e_phi_nor,        22) \
X(a, STATIC,   SINGULAR, UINT64,   time_process,     23)
#define protobuf_robot_var_info_t_CALLBACK NULL
#define protobuf_robot_var_info_t_DEFAULT NULL

#define protobuf_robot_info_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  state_info,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  var_info,          2)
#define protobuf_robot_info_rsp_t_CALLBACK NULL
#define protobuf_robot_info_rsp_t_DEFAULT NULL
#define protobuf_robot_info_rsp_t_state_info_MSGTYPE protobuf_robot_state_info_t
#define protobuf_robot_info_rsp_t_var_info_MSGTYPE protobuf_robot_var_info_t

#define protobuf_debug_msg_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1) \
X(a, STATIC,   SINGULAR, BYTES,    message,           2) \
X(a, STATIC,   SINGULAR, UENUM,    interface_dst,     3)
#define protobuf_debug_msg_t_CALLBACK NULL
#define protobuf_debug_msg_t_DEFAULT NULL

#define protobuf_robot_direction_cmd_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    cmd,               1)
#define protobuf_robot_direction_cmd_t_CALLBACK NULL
#define protobuf_robot_direction_cmd_t_DEFAULT NULL

#define protobuf_signs_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     bus_stop,          1) \
X(a, STATIC,   SINGULAR, BOOL,     children_crossing,   2) \
X(a, STATIC,   SINGULAR, BOOL,     green_light,       3) \
X(a, STATIC,   SINGULAR, BOOL,     left_turn_only,    4) \
X(a, STATIC,   SINGULAR, BOOL,     no_stopping,       5) \
X(a, STATIC,   SINGULAR, BOOL,     red_light,         6) \
X(a, STATIC,   SINGULAR, BOOL,     speed_limit_40,    7) \
X(a, STATIC,   SINGULAR, BOOL,     stop,              8)
#define protobuf_signs_t_CALLBACK NULL
#define protobuf_signs_t_DEFAULT NULL

#define protobuf_signs_info_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  signs_detected,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  signs_obey,        2)
#define protobuf_signs_info_t_CALLBACK NULL
#define protobuf_signs_info_t_DEFAULT NULL
#define protobuf_signs_info_t_signs_detected_MSGTYPE protobuf_signs_t
#define protobuf_signs_info_t_signs_obey_MSGTYPE protobuf_signs_t

#define protobuf_cv_command_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     process_crossroads,   1)
#define protobuf_cv_command_t_CALLBACK NULL
#define protobuf_cv_command_t_DEFAULT NULL

#define protobuf_direction_list_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    first,             1) \
X(a, STATIC,   SINGULAR, UENUM,    second,            2) \
X(a, STATIC,   SINGULAR, UENUM,    third,             3) \
X(a, STATIC,   SINGULAR, UENUM,    fourth,            4) \
X(a, STATIC,   SINGULAR, UENUM,    fifth,             5) \
X(a, STATIC,   SINGULAR, UENUM,    sixth,             6) \
X(a, STATIC,   SINGULAR, UENUM,    seventh,           7) \
X(a, STATIC,   SINGULAR, UENUM,    eighth,            8) \
X(a, STATIC,   SINGULAR, UENUM,    ninth,             9) \
X(a, STATIC,   SINGULAR, UENUM,    tenth,            10)
#define protobuf_direction_list_t_CALLBACK NULL
#define protobuf_direction_list_t_DEFAULT NULL

#define protobuf_network_packet_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hdr,               1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,none,params.none),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,network_ack,params.network_ack),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,network_status_get,params.network_status_get),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,netowrk_status_rsp,params.netowrk_status_rsp),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_cmd_start,params.robot_cmd_start),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_cmd_stop,params.robot_cmd_stop),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,fuzzy_coef_set,params.fuzzy_coef_set),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,fuzzy_coef_get,params.fuzzy_coef_get),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,fuzzy_coef_resp,params.fuzzy_coef_resp),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,speed_get,params.speed_get),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,speed_resp,params.speed_resp),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,speed_max_set,params.speed_max_set),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,speed_max_get,params.speed_max_get),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,speed_max_resp,params.speed_max_resp),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,time_get,params.time_get),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,time_set,params.time_set),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,time_rsp,params.time_rsp),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_process_state_get,params.robot_process_state_get),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_process_state_set,params.robot_process_state_set),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_process_state_rsp,params.robot_process_state_rsp),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_direct_state_get,params.robot_direct_state_get),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_direct_state_set,params.robot_direct_state_set),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_direct_state_rsp,params.robot_direct_state_rsp),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_state_get,params.robot_state_get),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_state_rsp,params.robot_state_rsp),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,traffic_detected,params.traffic_detected),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,vision_coordinate_detected,params.vision_coordinate_detected),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_control_cmd,params.robot_control_cmd),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,vision_start,params.vision_start),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,vision_stop,params.vision_stop),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_angle_get,params.robot_angle_get),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_angle_rsp,params.robot_angle_rsp),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_max_angle_get,params.robot_max_angle_get),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_max_angle_set,params.robot_max_angle_set),  35) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_max_angle_rsp,params.robot_max_angle_rsp),  36) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_info_get,params.robot_info_get),  37) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_info_rsp,params.robot_info_rsp),  38) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,debug_msg,params.debug_msg),  39) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,robot_direction_cmd,params.robot_direction_cmd),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,cv_command,params.cv_command),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,signs_info,params.signs_info),  42) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,direction_list,params.direction_list),  43)
#define protobuf_network_packet_t_CALLBACK NULL
#define protobuf_network_packet_t_DEFAULT NULL
#define protobuf_network_packet_t_hdr_MSGTYPE protobuf_hdr_t
#define protobuf_network_packet_t_params_none_MSGTYPE protobuf_network_none_t
#define protobuf_network_packet_t_params_network_ack_MSGTYPE protobuf_network_ack_t
#define protobuf_network_packet_t_params_network_status_get_MSGTYPE protobuf_network_status_get_t
#define protobuf_network_packet_t_params_netowrk_status_rsp_MSGTYPE protobuf_network_status_rsp_t
#define protobuf_network_packet_t_params_robot_cmd_start_MSGTYPE protobuf_robot_cmd_start_t
#define protobuf_network_packet_t_params_robot_cmd_stop_MSGTYPE protobuf_robot_cmd_stop_t
#define protobuf_network_packet_t_params_fuzzy_coef_set_MSGTYPE protobuf_fuzzy_coef_set_t
#define protobuf_network_packet_t_params_fuzzy_coef_get_MSGTYPE protobuf_fuzzy_coef_get_t
#define protobuf_network_packet_t_params_fuzzy_coef_resp_MSGTYPE protobuf_fuzzy_coef_resp_t
#define protobuf_network_packet_t_params_speed_get_MSGTYPE protobuf_speed_get_t
#define protobuf_network_packet_t_params_speed_resp_MSGTYPE protobuf_speed_resp_t
#define protobuf_network_packet_t_params_speed_max_set_MSGTYPE protobuf_speed_max_set_t
#define protobuf_network_packet_t_params_speed_max_get_MSGTYPE protobuf_speed_max_get_t
#define protobuf_network_packet_t_params_speed_max_resp_MSGTYPE protobuf_speed_max_resp_t
#define protobuf_network_packet_t_params_time_get_MSGTYPE protobuf_time_get_t
#define protobuf_network_packet_t_params_time_set_MSGTYPE protobuf_time_set_t
#define protobuf_network_packet_t_params_time_rsp_MSGTYPE protobuf_time_rsp_t
#define protobuf_network_packet_t_params_robot_process_state_get_MSGTYPE protobuf_robot_process_state_get_t
#define protobuf_network_packet_t_params_robot_process_state_set_MSGTYPE protobuf_robot_process_state_set_t
#define protobuf_network_packet_t_params_robot_process_state_rsp_MSGTYPE protobuf_robot_process_state_rsp_t
#define protobuf_network_packet_t_params_robot_direct_state_get_MSGTYPE protobuf_robot_direct_state_get_t
#define protobuf_network_packet_t_params_robot_direct_state_set_MSGTYPE protobuf_robot_direct_state_set_t
#define protobuf_network_packet_t_params_robot_direct_state_rsp_MSGTYPE protobuf_robot_direct_state_rsp_t
#define protobuf_network_packet_t_params_robot_state_get_MSGTYPE protobuf_robot_state_get_t
#define protobuf_network_packet_t_params_robot_state_rsp_MSGTYPE protobuf_robot_state_rsp_t
#define protobuf_network_packet_t_params_traffic_detected_MSGTYPE protobuf_traffic_detected_t
#define protobuf_network_packet_t_params_vision_coordinate_detected_MSGTYPE protobuf_vision_coordinate_detected_t
#define protobuf_network_packet_t_params_robot_control_cmd_MSGTYPE protobuf_robot_control_cmd_t
#define protobuf_network_packet_t_params_vision_start_MSGTYPE protobuf_vision_start_t
#define protobuf_network_packet_t_params_vision_stop_MSGTYPE protobuf_vision_stop_t
#define protobuf_network_packet_t_params_robot_angle_get_MSGTYPE protobuf_robot_angle_get_t
#define protobuf_network_packet_t_params_robot_angle_rsp_MSGTYPE protobuf_robot_angle_rsp_t
#define protobuf_network_packet_t_params_robot_max_angle_get_MSGTYPE protobuf_robot_max_angle_get_t
#define protobuf_network_packet_t_params_robot_max_angle_set_MSGTYPE protobuf_robot_max_angle_set_t
#define protobuf_network_packet_t_params_robot_max_angle_rsp_MSGTYPE protobuf_robot_max_angle_rsp_t
#define protobuf_network_packet_t_params_robot_info_get_MSGTYPE protobuf_robot_info_get_t
#define protobuf_network_packet_t_params_robot_info_rsp_MSGTYPE protobuf_robot_info_rsp_t
#define protobuf_network_packet_t_params_debug_msg_MSGTYPE protobuf_debug_msg_t
#define protobuf_network_packet_t_params_robot_direction_cmd_MSGTYPE protobuf_robot_direction_cmd_t
#define protobuf_network_packet_t_params_cv_command_MSGTYPE protobuf_cv_command_t
#define protobuf_network_packet_t_params_signs_info_MSGTYPE protobuf_signs_info_t
#define protobuf_network_packet_t_params_direction_list_MSGTYPE protobuf_direction_list_t

extern const pb_msgdesc_t protobuf_addr_t_msg;
extern const pb_msgdesc_t protobuf_network_status_get_t_msg;
extern const pb_msgdesc_t protobuf_network_status_rsp_t_msg;
extern const pb_msgdesc_t protobuf_network_none_t_msg;
extern const pb_msgdesc_t protobuf_network_ack_t_msg;
extern const pb_msgdesc_t protobuf_robot_cmd_start_t_msg;
extern const pb_msgdesc_t protobuf_robot_cmd_stop_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_3_positive_rule_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_5_rule_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_7_rule_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_9_rule_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_11_rule_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_coef_rule_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_5_rule_coef_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_3_rule_coef_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_7_rule_coef_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_11_rule_coef_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_3_positive_coef_rule_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_normalization_coef_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_coef_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_coef_set_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_coef_get_t_msg;
extern const pb_msgdesc_t protobuf_fuzzy_coef_resp_t_msg;
extern const pb_msgdesc_t protobuf_speed_get_t_msg;
extern const pb_msgdesc_t protobuf_speed_resp_t_msg;
extern const pb_msgdesc_t protobuf_speed_max_set_t_msg;
extern const pb_msgdesc_t protobuf_speed_max_get_t_msg;
extern const pb_msgdesc_t protobuf_speed_max_resp_t_msg;
extern const pb_msgdesc_t protobuf_hdr_t_msg;
extern const pb_msgdesc_t protobuf_time_get_t_msg;
extern const pb_msgdesc_t protobuf_time_set_t_msg;
extern const pb_msgdesc_t protobuf_time_rsp_t_msg;
extern const pb_msgdesc_t protobuf_robot_process_state_get_t_msg;
extern const pb_msgdesc_t protobuf_robot_process_state_set_t_msg;
extern const pb_msgdesc_t protobuf_robot_process_state_rsp_t_msg;
extern const pb_msgdesc_t protobuf_robot_direct_state_get_t_msg;
extern const pb_msgdesc_t protobuf_robot_direct_state_set_t_msg;
extern const pb_msgdesc_t protobuf_robot_direct_state_rsp_t_msg;
extern const pb_msgdesc_t protobuf_robot_state_get_t_msg;
extern const pb_msgdesc_t protobuf_robot_state_rsp_t_msg;
extern const pb_msgdesc_t protobuf_traffic_detected_t_msg;
extern const pb_msgdesc_t protobuf_vision_coordinate_detected_t_msg;
extern const pb_msgdesc_t protobuf_robot_control_cmd_t_msg;
extern const pb_msgdesc_t protobuf_vision_start_t_msg;
extern const pb_msgdesc_t protobuf_vision_stop_t_msg;
extern const pb_msgdesc_t protobuf_robot_angle_get_t_msg;
extern const pb_msgdesc_t protobuf_robot_angle_rsp_t_msg;
extern const pb_msgdesc_t protobuf_robot_max_angle_get_t_msg;
extern const pb_msgdesc_t protobuf_robot_max_angle_set_t_msg;
extern const pb_msgdesc_t protobuf_robot_max_angle_rsp_t_msg;
extern const pb_msgdesc_t protobuf_robot_info_get_t_msg;
extern const pb_msgdesc_t protobuf_robot_state_info_t_msg;
extern const pb_msgdesc_t protobuf_robot_var_info_t_msg;
extern const pb_msgdesc_t protobuf_robot_info_rsp_t_msg;
extern const pb_msgdesc_t protobuf_debug_msg_t_msg;
extern const pb_msgdesc_t protobuf_robot_direction_cmd_t_msg;
extern const pb_msgdesc_t protobuf_signs_t_msg;
extern const pb_msgdesc_t protobuf_signs_info_t_msg;
extern const pb_msgdesc_t protobuf_cv_command_t_msg;
extern const pb_msgdesc_t protobuf_direction_list_t_msg;
extern const pb_msgdesc_t protobuf_network_packet_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protobuf_addr_t_fields &protobuf_addr_t_msg
#define protobuf_network_status_get_t_fields &protobuf_network_status_get_t_msg
#define protobuf_network_status_rsp_t_fields &protobuf_network_status_rsp_t_msg
#define protobuf_network_none_t_fields &protobuf_network_none_t_msg
#define protobuf_network_ack_t_fields &protobuf_network_ack_t_msg
#define protobuf_robot_cmd_start_t_fields &protobuf_robot_cmd_start_t_msg
#define protobuf_robot_cmd_stop_t_fields &protobuf_robot_cmd_stop_t_msg
#define protobuf_fuzzy_3_positive_rule_t_fields &protobuf_fuzzy_3_positive_rule_t_msg
#define protobuf_fuzzy_5_rule_t_fields &protobuf_fuzzy_5_rule_t_msg
#define protobuf_fuzzy_7_rule_t_fields &protobuf_fuzzy_7_rule_t_msg
#define protobuf_fuzzy_9_rule_t_fields &protobuf_fuzzy_9_rule_t_msg
#define protobuf_fuzzy_11_rule_t_fields &protobuf_fuzzy_11_rule_t_msg
#define protobuf_fuzzy_coef_rule_t_fields &protobuf_fuzzy_coef_rule_t_msg
#define protobuf_fuzzy_5_rule_coef_t_fields &protobuf_fuzzy_5_rule_coef_t_msg
#define protobuf_fuzzy_3_rule_coef_t_fields &protobuf_fuzzy_3_rule_coef_t_msg
#define protobuf_fuzzy_7_rule_coef_t_fields &protobuf_fuzzy_7_rule_coef_t_msg
#define protobuf_fuzzy_11_rule_coef_t_fields &protobuf_fuzzy_11_rule_coef_t_msg
#define protobuf_fuzzy_3_positive_coef_rule_t_fields &protobuf_fuzzy_3_positive_coef_rule_t_msg
#define protobuf_fuzzy_normalization_coef_t_fields &protobuf_fuzzy_normalization_coef_t_msg
#define protobuf_fuzzy_coef_t_fields &protobuf_fuzzy_coef_t_msg
#define protobuf_fuzzy_coef_set_t_fields &protobuf_fuzzy_coef_set_t_msg
#define protobuf_fuzzy_coef_get_t_fields &protobuf_fuzzy_coef_get_t_msg
#define protobuf_fuzzy_coef_resp_t_fields &protobuf_fuzzy_coef_resp_t_msg
#define protobuf_speed_get_t_fields &protobuf_speed_get_t_msg
#define protobuf_speed_resp_t_fields &protobuf_speed_resp_t_msg
#define protobuf_speed_max_set_t_fields &protobuf_speed_max_set_t_msg
#define protobuf_speed_max_get_t_fields &protobuf_speed_max_get_t_msg
#define protobuf_speed_max_resp_t_fields &protobuf_speed_max_resp_t_msg
#define protobuf_hdr_t_fields &protobuf_hdr_t_msg
#define protobuf_time_get_t_fields &protobuf_time_get_t_msg
#define protobuf_time_set_t_fields &protobuf_time_set_t_msg
#define protobuf_time_rsp_t_fields &protobuf_time_rsp_t_msg
#define protobuf_robot_process_state_get_t_fields &protobuf_robot_process_state_get_t_msg
#define protobuf_robot_process_state_set_t_fields &protobuf_robot_process_state_set_t_msg
#define protobuf_robot_process_state_rsp_t_fields &protobuf_robot_process_state_rsp_t_msg
#define protobuf_robot_direct_state_get_t_fields &protobuf_robot_direct_state_get_t_msg
#define protobuf_robot_direct_state_set_t_fields &protobuf_robot_direct_state_set_t_msg
#define protobuf_robot_direct_state_rsp_t_fields &protobuf_robot_direct_state_rsp_t_msg
#define protobuf_robot_state_get_t_fields &protobuf_robot_state_get_t_msg
#define protobuf_robot_state_rsp_t_fields &protobuf_robot_state_rsp_t_msg
#define protobuf_traffic_detected_t_fields &protobuf_traffic_detected_t_msg
#define protobuf_vision_coordinate_detected_t_fields &protobuf_vision_coordinate_detected_t_msg
#define protobuf_robot_control_cmd_t_fields &protobuf_robot_control_cmd_t_msg
#define protobuf_vision_start_t_fields &protobuf_vision_start_t_msg
#define protobuf_vision_stop_t_fields &protobuf_vision_stop_t_msg
#define protobuf_robot_angle_get_t_fields &protobuf_robot_angle_get_t_msg
#define protobuf_robot_angle_rsp_t_fields &protobuf_robot_angle_rsp_t_msg
#define protobuf_robot_max_angle_get_t_fields &protobuf_robot_max_angle_get_t_msg
#define protobuf_robot_max_angle_set_t_fields &protobuf_robot_max_angle_set_t_msg
#define protobuf_robot_max_angle_rsp_t_fields &protobuf_robot_max_angle_rsp_t_msg
#define protobuf_robot_info_get_t_fields &protobuf_robot_info_get_t_msg
#define protobuf_robot_state_info_t_fields &protobuf_robot_state_info_t_msg
#define protobuf_robot_var_info_t_fields &protobuf_robot_var_info_t_msg
#define protobuf_robot_info_rsp_t_fields &protobuf_robot_info_rsp_t_msg
#define protobuf_debug_msg_t_fields &protobuf_debug_msg_t_msg
#define protobuf_robot_direction_cmd_t_fields &protobuf_robot_direction_cmd_t_msg
#define protobuf_signs_t_fields &protobuf_signs_t_msg
#define protobuf_signs_info_t_fields &protobuf_signs_info_t_msg
#define protobuf_cv_command_t_fields &protobuf_cv_command_t_msg
#define protobuf_direction_list_t_fields &protobuf_direction_list_t_msg
#define protobuf_network_packet_t_fields &protobuf_network_packet_t_msg

/* Maximum encoded size of messages (where known) */
#define PROTOBUF_PROTOCOL_PB_H_MAX_SIZE          protobuf_network_packet_t_size
#define protobuf_addr_t_size                     4
#define protobuf_cv_command_t_size               2
#define protobuf_debug_msg_t_size                207
#define protobuf_direction_list_t_size           20
#define protobuf_fuzzy_11_rule_coef_t_size       242
#define protobuf_fuzzy_11_rule_t_size            55
#define protobuf_fuzzy_3_positive_coef_rule_t_size 66
#define protobuf_fuzzy_3_positive_rule_t_size    15
#define protobuf_fuzzy_3_rule_coef_t_size        66
#define protobuf_fuzzy_5_rule_coef_t_size        110
#define protobuf_fuzzy_5_rule_t_size             25
#define protobuf_fuzzy_7_rule_coef_t_size        154
#define protobuf_fuzzy_7_rule_t_size             35
#define protobuf_fuzzy_9_rule_t_size             45
#define protobuf_fuzzy_coef_get_t_size           6
#define protobuf_fuzzy_coef_resp_t_size          628
#define protobuf_fuzzy_coef_rule_t_size          20
#define protobuf_fuzzy_coef_set_t_size           628
#define protobuf_fuzzy_coef_t_size               625
#define protobuf_fuzzy_normalization_coef_t_size 50
#define protobuf_hdr_t_size                      17
#define protobuf_network_ack_t_size              6
#define protobuf_network_none_t_size             6
#define protobuf_network_packet_t_size           650
#define protobuf_network_status_get_t_size       6
#define protobuf_network_status_rsp_t_size       6
#define protobuf_robot_angle_get_t_size          6
#define protobuf_robot_angle_rsp_t_size          5
#define protobuf_robot_cmd_start_t_size          6
#define protobuf_robot_cmd_stop_t_size           6
#define protobuf_robot_control_cmd_t_size        46
#define protobuf_robot_direct_state_get_t_size   6
#define protobuf_robot_direct_state_rsp_t_size   2
#define protobuf_robot_direct_state_set_t_size   2
#define protobuf_robot_direction_cmd_t_size      2
#define protobuf_robot_info_get_t_size           6
#define protobuf_robot_info_rsp_t_size           142
#define protobuf_robot_max_angle_get_t_size      6
#define protobuf_robot_max_angle_rsp_t_size      5
#define protobuf_robot_max_angle_set_t_size      5
#define protobuf_robot_process_state_get_t_size  6
#define protobuf_robot_process_state_rsp_t_size  2
#define protobuf_robot_process_state_set_t_size  2
#define protobuf_robot_state_get_t_size          6
#define protobuf_robot_state_info_t_size         8
#define protobuf_robot_state_rsp_t_size          4
#define protobuf_robot_var_info_t_size           129
#define protobuf_signs_info_t_size               36
#define protobuf_signs_t_size                    16
#define protobuf_speed_get_t_size                6
#define protobuf_speed_max_get_t_size            6
#define protobuf_speed_max_resp_t_size           5
#define protobuf_speed_max_set_t_size            5
#define protobuf_speed_resp_t_size               5
#define protobuf_time_get_t_size                 6
#define protobuf_time_rsp_t_size                 13
#define protobuf_time_set_t_size                 11
#define protobuf_traffic_detected_t_size         2
#define protobuf_vision_coordinate_detected_t_size 36
#define protobuf_vision_start_t_size             6
#define protobuf_vision_stop_t_size              6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
