/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protobuf_addr_t, protobuf_addr_t, AUTO)


PB_BIND(protobuf_network_status_get_t, protobuf_network_status_get_t, AUTO)


PB_BIND(protobuf_network_status_rsp_t, protobuf_network_status_rsp_t, AUTO)


PB_BIND(protobuf_network_none_t, protobuf_network_none_t, AUTO)


PB_BIND(protobuf_network_ack_t, protobuf_network_ack_t, AUTO)


PB_BIND(protobuf_robot_cmd_start_t, protobuf_robot_cmd_start_t, AUTO)


PB_BIND(protobuf_robot_cmd_stop_t, protobuf_robot_cmd_stop_t, AUTO)


PB_BIND(protobuf_fuzzy_3_positive_rule_t, protobuf_fuzzy_3_positive_rule_t, AUTO)


PB_BIND(protobuf_fuzzy_5_rule_t, protobuf_fuzzy_5_rule_t, AUTO)


PB_BIND(protobuf_fuzzy_7_rule_t, protobuf_fuzzy_7_rule_t, AUTO)


PB_BIND(protobuf_fuzzy_9_rule_t, protobuf_fuzzy_9_rule_t, AUTO)


PB_BIND(protobuf_fuzzy_11_rule_t, protobuf_fuzzy_11_rule_t, AUTO)


PB_BIND(protobuf_fuzzy_coef_rule_t, protobuf_fuzzy_coef_rule_t, AUTO)


PB_BIND(protobuf_fuzzy_5_rule_coef_t, protobuf_fuzzy_5_rule_coef_t, AUTO)


PB_BIND(protobuf_fuzzy_3_rule_coef_t, protobuf_fuzzy_3_rule_coef_t, AUTO)


PB_BIND(protobuf_fuzzy_7_rule_coef_t, protobuf_fuzzy_7_rule_coef_t, AUTO)


PB_BIND(protobuf_fuzzy_11_rule_coef_t, protobuf_fuzzy_11_rule_coef_t, 2)


PB_BIND(protobuf_fuzzy_3_positive_coef_rule_t, protobuf_fuzzy_3_positive_coef_rule_t, AUTO)


PB_BIND(protobuf_fuzzy_normalization_coef_t, protobuf_fuzzy_normalization_coef_t, AUTO)


PB_BIND(protobuf_fuzzy_coef_t, protobuf_fuzzy_coef_t, 2)


PB_BIND(protobuf_fuzzy_coef_set_t, protobuf_fuzzy_coef_set_t, 2)


PB_BIND(protobuf_fuzzy_coef_get_t, protobuf_fuzzy_coef_get_t, AUTO)


PB_BIND(protobuf_fuzzy_coef_resp_t, protobuf_fuzzy_coef_resp_t, 2)


PB_BIND(protobuf_speed_get_t, protobuf_speed_get_t, AUTO)


PB_BIND(protobuf_speed_resp_t, protobuf_speed_resp_t, AUTO)


PB_BIND(protobuf_speed_max_set_t, protobuf_speed_max_set_t, AUTO)


PB_BIND(protobuf_speed_max_get_t, protobuf_speed_max_get_t, AUTO)


PB_BIND(protobuf_speed_max_resp_t, protobuf_speed_max_resp_t, AUTO)


PB_BIND(protobuf_hdr_t, protobuf_hdr_t, AUTO)


PB_BIND(protobuf_time_get_t, protobuf_time_get_t, AUTO)


PB_BIND(protobuf_time_set_t, protobuf_time_set_t, AUTO)


PB_BIND(protobuf_time_rsp_t, protobuf_time_rsp_t, AUTO)


PB_BIND(protobuf_robot_process_state_get_t, protobuf_robot_process_state_get_t, AUTO)


PB_BIND(protobuf_robot_process_state_set_t, protobuf_robot_process_state_set_t, AUTO)


PB_BIND(protobuf_robot_process_state_rsp_t, protobuf_robot_process_state_rsp_t, AUTO)


PB_BIND(protobuf_robot_direct_state_get_t, protobuf_robot_direct_state_get_t, AUTO)


PB_BIND(protobuf_robot_direct_state_set_t, protobuf_robot_direct_state_set_t, AUTO)


PB_BIND(protobuf_robot_direct_state_rsp_t, protobuf_robot_direct_state_rsp_t, AUTO)


PB_BIND(protobuf_robot_state_get_t, protobuf_robot_state_get_t, AUTO)


PB_BIND(protobuf_robot_state_rsp_t, protobuf_robot_state_rsp_t, AUTO)


PB_BIND(protobuf_traffic_detected_t, protobuf_traffic_detected_t, AUTO)


PB_BIND(protobuf_vision_coordinate_detected_t, protobuf_vision_coordinate_detected_t, AUTO)


PB_BIND(protobuf_robot_control_cmd_t, protobuf_robot_control_cmd_t, AUTO)


PB_BIND(protobuf_vision_start_t, protobuf_vision_start_t, AUTO)


PB_BIND(protobuf_vision_stop_t, protobuf_vision_stop_t, AUTO)


PB_BIND(protobuf_robot_angle_get_t, protobuf_robot_angle_get_t, AUTO)


PB_BIND(protobuf_robot_angle_rsp_t, protobuf_robot_angle_rsp_t, AUTO)


PB_BIND(protobuf_robot_max_angle_get_t, protobuf_robot_max_angle_get_t, AUTO)


PB_BIND(protobuf_robot_max_angle_set_t, protobuf_robot_max_angle_set_t, AUTO)


PB_BIND(protobuf_robot_max_angle_rsp_t, protobuf_robot_max_angle_rsp_t, AUTO)


PB_BIND(protobuf_robot_info_get_t, protobuf_robot_info_get_t, AUTO)


PB_BIND(protobuf_robot_state_info_t, protobuf_robot_state_info_t, AUTO)


PB_BIND(protobuf_robot_var_info_t, protobuf_robot_var_info_t, AUTO)


PB_BIND(protobuf_robot_info_rsp_t, protobuf_robot_info_rsp_t, AUTO)


PB_BIND(protobuf_debug_msg_t, protobuf_debug_msg_t, AUTO)


PB_BIND(protobuf_robot_direction_cmd_t, protobuf_robot_direction_cmd_t, AUTO)


PB_BIND(protobuf_signs_t, protobuf_signs_t, AUTO)


PB_BIND(protobuf_signs_info_t, protobuf_signs_info_t, AUTO)


PB_BIND(protobuf_cv_command_t, protobuf_cv_command_t, AUTO)


PB_BIND(protobuf_direction_list_t, protobuf_direction_list_t, AUTO)


PB_BIND(protobuf_network_packet_t, protobuf_network_packet_t, 2)





















